SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_VERTICES = 8  # Number of points for asteroid shape
ASTEROID_IRREGULARITY = 0.4  # How irregular the shape can be (0-1)

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200 
PLAYER_START_LIVES = 3
PLAYER_RESPAWN_TIME = 2.0  # seconds of invulnerability after respawning
PLAYER_SPAWN_X = SCREEN_WIDTH / 2
PLAYER_SPAWN_Y = SCREEN_HEIGHT / 2
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5
SHOT_COLOR = (255, 0, 0)

SCORE_LARGE_ASTEROID = 20
SCORE_MEDIUM_ASTEROID = 50
SCORE_SMALL_ASTEROID = 100
# Explosion settings
EXPLOSION_PARTICLE_COUNT = 15  # Number of particles per explosion
EXPLOSION_PARTICLE_SPEED = 200  # Base speed for particles
EXPLOSION_PARTICLE_LIFETIME = 0.5  # How long particles last in seconds
EXPLOSION_PARTICLE_SIZE = 2  # Size of each particle